export interface WillData {
  user: {
    name: string
    address?: string
    walletAddress?: string
  }
  wallets: Array<{
    blockchain: string
    address: string
    assets: Array<{
      symbol: string
      name: string
      balance: string
    }>
  }>
  beneficiaries: Array<{
    fullName: string
    relationship: string
    ethAddress: string
    phoneNumber: string
    email: string
    allocationPercentage: number
  }>
  generatedAt: Date
}

export const generateLegalTemplate = (data: WillData): string => {
  const currentDate = data.generatedAt.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })

  return `
DIGITAL ASSET INHERITANCE ADDENDUM
LastWish.eth Platform

Generated on: ${currentDate}

I, ${data.user.name || 'User'}, being of sound mind and disposing memory, do hereby make this Digital Asset Inheritance Addendum to supplement my Last Will and Testament regarding the distribution of my cryptocurrency and digital assets.

SECTION 1: DIGITAL ASSET INVENTORY

I hereby declare that I own and control the following digital assets through verified wallet addresses:

${data.wallets.map((wallet, index) => `
${index + 1}. ${wallet.blockchain.toUpperCase()} WALLET
   Address: ${wallet.address}
   Assets:
${wallet.assets.map(asset => `   - ${asset.balance} ${asset.symbol} (${asset.name})`).join('\n')}
`).join('\n')}

SECTION 2: PROOF OF OWNERSHIP

I have cryptographically signed messages with each of the above wallet addresses to prove my ownership and control of these digital assets. These signatures are recorded and verified through the LastWish.eth platform.

SECTION 3: BENEFICIARY DESIGNATIONS

I hereby designate the following individuals as beneficiaries of my digital assets:

${data.beneficiaries.map((beneficiary, index) => `
${index + 1}. ${beneficiary.fullName}
   Relationship: ${beneficiary.relationship}
   Ethereum Address: ${beneficiary.ethAddress}
   Phone: ${beneficiary.phoneNumber}
   Email: ${beneficiary.email}
   Allocation: ${beneficiary.allocationPercentage}% of total digital assets
`).join('\n')}

SECTION 4: DISTRIBUTION INSTRUCTIONS

Upon my death, I direct that my digital assets be distributed to the above-named beneficiaries according to the specified percentages. The distribution should be made to their designated Ethereum addresses or other compatible blockchain addresses.

SECTION 5: ACCESS INSTRUCTIONS

My digital assets are secured through various wallet applications and hardware devices. My designated executor or beneficiaries should:

1. Contact the LastWish.eth platform for assistance with asset recovery
2. Provide proper legal documentation of my death
3. Follow the platform's verification procedures
4. Coordinate with legal counsel familiar with digital asset inheritance

SECTION 6: LEGAL DISCLAIMERS

This addendum is intended to supplement, not replace, my primary Last Will and Testament. I acknowledge that:

1. Digital asset laws vary by jurisdiction and continue to evolve
2. Technical challenges may affect asset recovery
3. Private keys or seed phrases may be required for asset access
4. Professional legal and technical assistance is recommended
5. The LastWish.eth platform provides tools but not legal advice

SECTION 7: UPDATES AND REVISIONS

This digital asset inventory and beneficiary designations may be updated through the LastWish.eth platform. The most recent version supersedes all previous versions.

SECTION 8: EXECUTION

By generating this document through the LastWish.eth platform and providing cryptographic signatures, I affirm that this represents my true intentions regarding my digital assets.

Signature: _________________________________
${data.user.name || 'User'}

Date: ${currentDate}

---

IMPORTANT NOTICE: This document is generated by LastWish.eth, a digital asset inheritance planning tool. This is not a substitute for professional legal advice. Please consult with an attorney familiar with digital asset inheritance laws in your jurisdiction to ensure this addendum is properly integrated with your estate planning documents.

For technical support or asset recovery assistance, contact:
LastWish.eth Platform
Generated via blockchain-verified signatures
Document ID: ${Math.random().toString(36).substr(2, 9).toUpperCase()}
`
}

