[build]
  command = "npm run build"
  publish = ".next"

[[edge_functions]]
  path = "/api/*"
  function = "server"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"