[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Environment variables (set these in Netlify dashboard)
# ALCHEMY_KEY = "your_alchemy_api_key"
# COVALENT_KEY = "your_covalent_api_key"
# WEB3_STORAGE_TOKEN = "your_web3_storage_token"
# N8N_WEBHOOK_URL = "your_n8n_webhook_url"
# ETHERSCAN_KEY = "your_etherscan_api_key"
# PAYMENT_RECEIVER = "0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b"

